// About.js
export const about = "About"
export const about_text_para_one = "Car shopping in Chicagoland and NW Indiana couldn't be easier thanks to DriveChicago.com, the area's most comprehensive, local online source for researching and purchasing new and used cars."
export const about_text_para_two = "DriveChicago.com is owned and operated by the Chicago Automobile Trade Association, producers of the Chicago Auto Show. With more than 100,000 new and used vehicles, it is Chicagoland's largest local inventory listing."
export const about_text_para_three = " DriveChicago.com is fueled by the new and used vehicle inventories of more than 400 Chicagoland dealerships. You'll find virtually every vehicle in town from virtually every dealer in town!"
export const about_text_para_four = "DriveChicago.com is also on the radio. Listen as DriveChicago.com General Manager Mark Bilek and Chicago Auto Show Director of Marketing Jim OBrill are joined by host Robert Martier on the DriveChicago radio show on WLS AM890 Saturday mornings at 8 AM."
export const about_text_para_five = "We like to think of ourselves as relentlessly local. After all, Chicago area automotive shoppers want a local selection and we've got the largest! Unlike national sites, our focus is on local comparisons and local contacts, and when you decide to take that new car for spin, it's waiting for you just down the street. We hope you enjoy the search. It's the CLICK and EASY way to buy a vehicle because DriveChicago.com has virtually every vehicle in town."

// Account Settings
export const accSettings = " Account Settings"
export const name = "Name:"
export const joeSmith = "Joe Smith"
export const email = "E-mail:"
export const emailPlaceholder = "email@email.com"
export const password = "Password:"
export const stars = "********"
export const zipCode = "Zip Code:"
export const zipPlaceHolder = "60525"
export const updateInfo = "Update Info"

// Article.js
export const reviewsTitle = "Reviews and Road Tests"

// ArticleHome.js

//Calculator.js
export const newState = "new"
export const usedState = "used"
export const financeCalculator = "Finance Calculator"
export const financeSubHeader = "Use our built-in finance calculator to help determine your automobile needs."
export const estimateMonthlyPayment = "Estimate Your Monthly Payment" 
export const priceLabel = "Price"
export const moneyPlaceholder = "$50,000"
export const newOrUsed = "Is This a New or Used Car?"
export const newCar = "New Car"
export const usedCar = "Used Car"
export const creditRatingText = "Credit Rating"
export const ficoScoreExcellent = "FICO Score (781 - 850)"
export const ficoScoreVeryGood = "FICO Score (661 - 780)"
export const ficoScoreGood = "FICO Score (601 - 660)"
export const ficoScoreFair = "FICO Score (501 - 600)"
export const ficoScorePoor = "FICO Score (300 - 500)"
export const downPaymentOptionalText = "Down Payment (optional)"
export const tradeInValueOptional = "Trade-in Value (optional)"
export const loanLength = "Length of Loan (in months)"
export const disclaimerNote = "*Rates based on Experian's State of the Automotive Finance Market Report: Q3 2023"
export const secondDisclaimerNote = "*Additional fees and sales tax not included in estimations"
export const estimatedPayment = "Your Estimated Payment"
export const loanDetails = "Loan Details"
export const carPrice = "Car Price"
export const downPaymentText = "Down Payment"
export const tradeInValueText = "Trade-in Value"
export const totalLoanAmountText = "Total Loan Amount"
export const totalInterestText = "Total Interest"
export const totalLoanAndInterest = "Total Loan & Interest"
export const monthlyPaymentText = "Monthly Payment"
export const shopCarsText = "Shop Cars"
export const faqText = "FAQ"
    // not complete